(define (square x) (* x x))
(define (sum-of-squares x y) (+ (square x) (square y)))
(define (sum-of-squares-two-largest x y z) (cond ((and (> x z) (> y z)) (sum-of-squares x y))
                          ((and (>= x y) (>= z y)) (sum-of-squares x z))
                          ((and (>= y x) (>= z x)) (sum-of-squares y z))))
(print (sum-of-squares-two-largest 4 5 4))
